Revert "Removes unnecessary utf-8 encoding"
This reverts commit 4076dce887b84ab4298c54eb422a069e006e590b.

Commit above is the cause for UTF errors such as:
[root@undercloud-0 ~]# /usr/libexec/openstack-monitoring/checks/oschecks-check_amqp neutron-server
Traceback (most recent call last):
  File "/usr/libexec/openstack-monitoring/checks/oschecks-check_amqp", line 6, in <module>
    from oschecks.amqp import main
  File "/usr/lib/python2.7/site-packages/oschecks/amqp.py", line 23, in <module>
    from oschecks import utils
  File "/usr/lib/python2.7/site-packages/oschecks/utils.py", line 5
SyntaxError: Non-ASCII character '\xc2' in file /usr/lib/python2.7/site-packages/oschecks/utils.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Change-Id: I94faa925bb642621bc8688addca60168889e93d3